config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'home#index'

  devise_for(:user, {
    class_name: 'Spree::User',
    singular: :spree_user,
    controllers: {
      sessions: 'user_sessions',
      registrations: 'user_registrations',
      passwords: 'user_passwords',
      confirmations: 'user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' }
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  resources :cart_line_items, only: :create

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale
  get '/contact_us', to: 'home#contact_us', as: :contact_us

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order
  get '/search_by_taxon', to: 'products#search_by_taxon'

  resources :orders, only: :show do
    resources :coupon_codes, only: :create
  end

  resource :cart, only: [:edit, :update] do
    put 'empty'
  end

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/spree/order.rb
# frozen_string_literal: true

module Spree
    # The customers cart until completed, then acts as permanent record of the transaction.
    #
    # `Spree::Order` is the heart of the Solidus system, as it acts as the customer's
    # cart as they shop. Once an order is complete, it serves as the
    # permanent record of their purchase. It has many responsibilities:
    #
    # * Records and validates attributes like `total` and relationships like
    # `Spree::LineItem` as an ActiveRecord model.
    #
    # * Implements a customizable state machine to manage the lifecycle of an order.
    #
    # * Implements business logic to provide a single interface for quesitons like
    # `checkout_allowed?` or `payment_required?`.
    #
    #  * Implements an interface for mutating the order with methods like
    # `empty!` and `fulfill!`.
    #
    class Order < Spree::Base
      ORDER_NUMBER_LENGTH  = 9
      ORDER_NUMBER_LETTERS = false
      ORDER_NUMBER_PREFIX  = 'R'
  
      include ::Spree::Config.state_machines.order
  
      include Spree::Order::Payments
  
      class InsufficientStock < StandardError
        attr_reader :items
  
        def initialize(message = nil, items: {})
          @items = items
          super message
        end
      end
      class CannotRebuildShipments < StandardError; end
  
      extend Spree::DisplayMoney
      money_methods(
        :outstanding_balance,
        :item_total,
        :adjustment_total,
        :included_tax_total,
        :additional_tax_total,
        :tax_total,
        :shipment_total,
        :total,
        :order_total_after_store_credit,
        :total_available_store_credit,
        :item_total_before_tax,
        :shipment_total_before_tax,
        :item_total_excluding_vat
      )
      alias :display_ship_total :display_shipment_total
  
      checkout_flow do
        go_to_state :address
        #go_to_state :delivery
        #go_to_state :payment, if: ->(order) { order.payment_required? }
        #go_to_state :confirm
      end
  
      self.allowed_ransackable_associations = %w[shipments user order_promotions promotions bill_address ship_address line_items]
      self.allowed_ransackable_attributes = %w[completed_at created_at email number state payment_state shipment_state total store_id]
  
      attr_reader :coupon_code
      attr_accessor :temporary_address
  
      attr_accessor :temporary_payment_source
  
      # Customer info
      belongs_to :user, class_name: Spree::UserClassHandle.new, optional: true
      belongs_to :bill_address, foreign_key: :bill_address_id, class_name: 'Spree::Address', optional: true
      alias_attribute :billing_address, :bill_address
  
      belongs_to :ship_address, foreign_key: :ship_address_id, class_name: 'Spree::Address', optional: true
      alias_attribute :shipping_address, :ship_address
      alias_attribute :ship_total, :shipment_total
  
      belongs_to :store, class_name: 'Spree::Store', optional: true
  
      # Items
      has_many :line_items, -> { order(:created_at, :id) }, dependent: :destroy, inverse_of: :order
      has_many :variants, through: :line_items
      has_many :products, through: :variants
  
      # Shipping
      has_many :shipments, dependent: :destroy, inverse_of: :order do
        def states
          pluck(:state).uniq
        end
      end
      has_many :inventory_units, through: :shipments
      has_many :cartons, -> { distinct }, through: :inventory_units
  
      # Adjustments and promotions
      has_many :adjustments, -> { order(:created_at) }, as: :adjustable, inverse_of: :adjustable, dependent: :destroy
      has_many :line_item_adjustments, through: :line_items, source: :adjustments
      has_many :shipment_adjustments, through: :shipments, source: :adjustments
      has_many :all_adjustments,
               class_name: 'Spree::Adjustment',
               foreign_key: :order_id,
               dependent: :destroy,
               inverse_of: :order
      has_many :order_promotions, class_name: 'Spree::OrderPromotion'
      has_many :promotions, through: :order_promotions
  
      # Payments
      has_many :payments, dependent: :destroy, inverse_of: :order
      has_many :valid_store_credit_payments, -> { store_credits.valid }, inverse_of: :order, class_name: 'Spree::Payment', foreign_key: :order_id
  
      # Returns
      has_many :return_authorizations, dependent: :destroy, inverse_of: :order
      has_many :return_items, through: :inventory_units
      has_many :customer_returns, -> { distinct }, through: :return_items
      has_many :reimbursements, inverse_of: :order
      has_many :refunds, through: :payments
  
      # Logging
      has_many :state_changes, as: :stateful
      belongs_to :created_by, class_name: Spree::UserClassHandle.new, optional: true
      belongs_to :approver, class_name: Spree::UserClassHandle.new, optional: true
      belongs_to :canceler, class_name: Spree::UserClassHandle.new, optional: true
  
      accepts_nested_attributes_for :line_items
      accepts_nested_attributes_for :bill_address
      accepts_nested_attributes_for :ship_address
      accepts_nested_attributes_for :payments
      accepts_nested_attributes_for :shipments
  
      # Needs to happen before save_permalink is called
      before_validation :associate_store
      before_validation :set_currency
      before_validation :generate_order_number, on: :create
      before_validation :assign_billing_to_shipping_address, if: :use_billing?
      attr_accessor :use_billing
  
      before_create :create_token
      before_create :link_by_email
  
      validates :email, presence: true, if: :email_required?
      validates :email, 'spree/email' => true, allow_blank: true
      validates :guest_token, presence: { allow_nil: true }
      validates :number, presence: true, uniqueness: { allow_blank: true, case_sensitive: true }
      validates :store_id, presence: true
  
      def self.find_by_param(value)
        find_by number: value
      end
  
      def self.find_by_param!(value)
        find_by! number: value
      end
  
      delegate :name, to: :bill_address, prefix: true, allow_nil: true
      alias_method :billing_name, :bill_address_name
  
      class_attribute :line_item_comparison_hooks
      self.line_item_comparison_hooks = Set.new
  
      scope :created_between, ->(start_date, end_date) { where(created_at: start_date..end_date) }
      scope :completed_between, ->(start_date, end_date) { where(completed_at: start_date..end_date) }
  
      scope :by_store, ->(store) { where(store_id: store.id) }
  
      # shows completed orders first, by their completed_at date, then uncompleted orders by their created_at
      scope :reverse_chronological, -> { order(Arel.sql('spree_orders.completed_at IS NULL'), completed_at: :desc, created_at: :desc) }
  
      def self.by_customer(customer)
        joins(:user).where("#{Spree.user_class.table_name}.email" => customer)
      end
  
      def self.by_state(state)
        where(state: state)
      end
  
      def self.complete
        where.not(completed_at: nil)
      end
  
      def self.incomplete
        where(completed_at: nil)
      end
  
      def self.canceled
        where(state: 'canceled')
      end
  
      def self.not_canceled
        where.not(state: 'canceled')
      end
  
      # Use this method in other gems that wish to register their own custom logic
      # that should be called when determining if two line items are equal.
      def self.register_line_item_comparison_hook(hook)
        line_item_comparison_hooks.add(hook)
      end
  
      # For compatiblity with Calculator::PriceSack
      def amount
        line_items.sum(&:amount)
      end
  
      def item_total_before_tax
        line_items.to_a.sum(&:total_before_tax)
      end
  
      def shipment_total_before_tax
        shipments.to_a.sum(&:total_before_tax)
      end
  
      # Sum of all line item amounts pre-tax
      def item_total_excluding_vat
        line_items.to_a.sum(&:total_excluding_vat)
      end
  
      def currency
        self[:currency] || Spree::Config[:currency]
      end
  
      def shipping_discount
        shipment_adjustments.credit.eligible.sum(:amount) * - 1
      end
  
      def to_param
        number
      end
  
      def completed?
        completed_at.present?
      end
  
      # Indicates whether or not the user is allowed to proceed to checkout.
      # Currently this is implemented as a check for whether or not there is at
      # least one LineItem in the Order.  Feel free to override this logic in your
      # own application if you require additional steps before allowing a checkout.
      def checkout_allowed?
        line_items.count > 0
      end
  
      # Is this a free order in which case the payment step should be skipped
      def payment_required?
        total > 0
      end
  
      def backordered?
        shipments.any?(&:backordered?)
      end
  
      # Returns the address for taxation based on configuration
      def tax_address
        if Spree::Config[:tax_using_ship_address]
          ship_address
        else
          bill_address
        end || store&.default_cart_tax_location
      end
  
      def updater
        @updater ||= Spree::OrderUpdater.new(self)
      end
  
      def recalculate
        updater.update
      end
  
      def assign_billing_to_shipping_address
        self.ship_address = bill_address if bill_address
        true
      end
  
      def allow_cancel?
        return false unless completed? && state != 'canceled'
        shipment_state.nil? || %w{ready backorder pending}.include?(shipment_state)
      end
  
      def all_inventory_units_returned?

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < StoreController
  helper 'spree/products', 'orders'

  respond_to :html

  before_action :store_guest_token

  def show
    @order = Spree::Order.find_by!(number: params[:id])
    authorize! :show, @order, cookies.signed[:guest_token]
  end

  private

  def accurate_title
    t('spree.order_number', number: @order.number)
  end

  def store_guest_token
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module OrdersHelper
  include TruncateHtmlHelper

  def truncated_product_description(product)
    truncate_html(raw(product.description))
  end

  def order_just_completed?(order)
    flash[:order_completed] && order.present?
  end
end

app/views/spree/admin/orders/_adjustments.html.erb
<!--<fieldset class="no-border-bottom">
  <legend><%= title %></legend>
  <table>
    <thead>
      <tr>
        <th><%= Spree::Adjustment.human_attribute_name(:name) %></th>
        <th><%= Spree::Adjustment.human_attribute_name(:amount) %></th>
      </tr>
    </thead>
    <tbody data-hook="order_details_adjustments">
      <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %>:</td>
          <td class="total"><span><%= Spree::Money.new(adjustments.sum(&:amount), currency: adjustments.first.order.try(:currency)) %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>-->

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render partial: 'spree/shared/error_messages', locals: { target: @line_item } %>
  <% end %>

  <%= render :partial => "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: { order: order } %>

  <%= render "spree/admin/orders/order_details", { order: order } %>

  <script>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
            shipments.push(<%== shipment.as_json(root: false, only: [:id, :tracking, :number, :state, :stock_location_id], include: [:inventory_units, :stock_location]).to_json %>);
    <% end %>
  </script>
</div>

app/views/spree/admin/orders/_order_details.html.erb
<div class="js-order-line-item-adjustments <%= "hidden" if order.line_item_adjustments.eligible.none? %>">
  <!--<%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.line_item_adjustments,
      order: order,
      title: t('spree.line_item_adjustments')
    }
  %>
</div>
<div class="js-order-shipment-adjustments <%= "hidden" if order.shipment_adjustments.eligible.none? %>">
  <%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.shipment_adjustments,
      order: order,
      title: t('spree.shipment_adjustments')
    }
  %>
</div>
<div class="js-order-adjustments <%= "hidden" if order.adjustments.eligible.none? %>">
  <%=
    render "spree/admin/orders/adjustments", {
      adjustments: order.adjustments,
      order: order,
      title: t('spree.order_adjustments')
    }
  %>-->
</div>

<fieldset class="no-border-bottom <%= "hidden" if order.line_items.none? %>" id="order-total" data-hook="order_details_total">
  <legend><%= t('spree.order_total') %></legend>
  <span class="order-total"><%= order.display_total %></span>
</fieldset>

app/views/spree/admin/orders/_shipment.html.erb
<%
  manifest_items = Spree::ShippingManifest.new(
    inventory_units: shipment.inventory_units.where(carton_id: nil),
  ).items.sort_by { |item| item.line_item.created_at }
%>

<div id="<%= "shipment_#{shipment.id}" %>" class="js-shipment-edit" data-hook="admin_shipment_form">
  <!--<fieldset class="no-border-bottom">
    <legend align="center" class="stock-location" data-hook="stock-location">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <span class="shipment-state"><%= t(shipment.state, scope: "spree.shipment_states") %></span>
      <%= t('spree.package_from') %>
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.stock_location.name %>'</strong>
    </legend>

    <% if shipment.ready? && can?(:ship, shipment) %>
      <%= form_tag("#", class: "admin-ship-shipment") do %>
        <label>
          <%= check_box_tag :send_mailer, true, true %>
          <%= t('spree.send_mailer') %>
        </label>
        <%= submit_tag t('spree.actions.ship'), class: "ship-shipment-button" %>
      <% end %>
    <% end %>
  </fieldset>-->

  <table class="stock-contents shipment index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 17.5%;">
      <col style="width: 30%;">
      <col style="width: 12.5%;">
      <col style="width: 15%;">
      <col style="width: 15%;">
      <col style="width: 10%;">
    </colgroup>

    <thead>
      <tr>
        <th colspan="2"><%= Spree::LineItem.human_attribute_name(:description) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
        <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
        <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions"></th>
      </tr>
    </thead>

    <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/shipment_manifest', { shipment_number: shipment.number, shipment_manifest: manifest_items } %>

      <!--<% unless shipment.shipped? %>
        <tr class="edit-shipping-method vertical-middle">
        </tr>
      <% end %>

      <tr class="edit-tracking vertical-middle">
      </tr>-->

      <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= t('spree.special_instructions') %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/admin/orders/_shipment_manifest.html.erb
<% shipment_manifest.each do |item| %>
  <tr class="stock-item"
      data-item-quantity="<%= item.quantity %>"
      data-variant-id="<%= item.variant.id %>"
      >
    <td class="item-image align-center">
      <%= render 'spree/admin/shared/image',
        image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
        size: :mini %>
    </td>
    <td class="item-name">
      <%= link_to item.variant.product.name, edit_admin_product_path(item.variant.product) %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong> <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price"><%= item.line_item.single_money.to_html %></td>
    <td class="item-qty-show">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= t(state, scope: 'spree.inventory_states') %>
        <% end %>
    </td>
    <td class="item-total"><%= item.line_item.display_amount %></td>

    <td class="cart-item-delete actions" data-hook="cart_item_delete">
      <% if can? :update, item %>
        <!--<%= button_tag '', class: 'split-item icon_link fa fa-arrows-h no-text with-tip', data: { action: 'edit', 'variant-id' => item.variant.id }, title: t('spree.actions.split'), type: :button %>-->
        <%= button_tag '', class: 'delete-item fa fa-trash no-text with-tip', data: { action: 'remove', 'variant-id' => item.variant.id }, title: t('spree.actions.delete'), type: :button %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Order)) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_order'), new_admin_order_url, id: 'admin_new_order', class: 'btn btn-primary' %>
  </li>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter_title do %>
  <%= t('spree.filter') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="field-block col-12 col-md-6 col-lg-4 col-xl-3">
          <div class="date-range-filter field">
            <%= label_tag :q_created_at_gt, t('spree.date_range') %>
            <div class="date-range-fields input-group">
              <%= f.text_field :created_at_gt, class: 'datepicker form-control datepicker-from', value: params[:q][:created_at_gt], placeholder: t('spree.start') %>

              <div class="input-group-prepend input-group-append">
                <span class="input-group-text range-divider">
                  <i class="fa fa-arrow-right"></i>
                </span>
              </div>

              <%= f.text_field :created_at_lt, class: 'datepicker form-control datepicker-to', value: params[:q][:created_at_lt], placeholder: t('spree.stop') %>
            </div>
          </div>

          <!--<div class="field">
            <%= label_tag :q_state_eq, t('spree.status') %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [t(s.name, scope: 'spree.order_state'), s.value]}, {include_blank: true}, class: 'custom-select fullwidth' %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.promotion') %>
            <%= f.text_field :order_promotions_promotion_code_value_start, size: 25 %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.shipment_number') %>
            <%= f.text_field :shipments_number_start %>
          </div>

          <div class="field">
            <%= label_tag :q_shipment_state, t('spree.shipment_state') %>
            <%= f.select :shipment_state_eq, %i[backorder canceled partial pending ready shipped].map { |state| [t("spree.shipment_states.#{state}"), state] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
          </div>-->
        </div>

        <div class="col-12 col-md-6 col-lg-4 col-xl-6">
          <div class="row">
            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_number_start, t('spree.order_number', number: '') %>
                <%= f.text_field :number_start %>
              </div>

              <div class="field">
                <%= label_tag :q_email_start, t('spree.email') %>
                <%= f.text_field :email_start %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_bill_address_name_cont, t('spree.name_contains') %>
                <%= f.text_field :bill_address_name_cont, size: 25 %>
              </div>
            </div>

            <!--<div class="col-12 col-xl-6">
              <div class="field" data-hook="sku-select">
                <%= label_tag :q_line_items_variant_id_in, t('spree.variant') %>
                <%= f.text_field :line_items_variant_id_in, class: "variant_autocomplete fullwidth" %>
              </div>
            </div>-->
          </div>
        </div>

        <!--<div class="col-12 col-md-6 col-lg-4 col-xl-3">
          <% if Spree::Store.count > 1 %>
            <div class="field">
              <%= label_tag :q_store_id_eq, t('spree.store') %>
              <%= f.select :store_id_eq, Spree::Store.all.map { |s| [s.name, s.id] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
            </div>
          <% end %>

          <div class="field checkbox">
            <label>
              <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
              <%= t('spree.show_only_complete_orders') %>
            </label>
          </div>
        </div>-->

      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button_tag t('spree.filter_results'), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>

<% if @orders.any? %>
  <table class="index" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 13%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 12%;">
       <% if Spree::Order.checkout_step_names.include?(:delivery) %>
         <col style="width: 12%;">
       <% end %>
       <col style="width: 25%;">
       <col style="width: 10%;">
       <col style="width: 8%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at %></th>
        <% else %>
          <th><%= sort_link @search, :created_at %></th>
        <% end %>
        <th><%= sort_link @search, :number %></th>
        <th><%= sort_link @search, :state %></th>
        <th><%= sort_link @search, :payment_state %></th>
        <!--<% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state %></th>
        <% end %>-->
        <th><%= sort_link @search, :email %></th>
        <th class="align-right"><%= sort_link @search, :total %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows">
        <td><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
        <td><%= order.number %></td>  <!--  <td><%= link_to order.number, edit_admin_order_path(order) %></td> -->
        <td>
          <span class="pill pill-<%= order.state %>">
            <%= t(order.state, scope: 'spree.order_state') %>
          </span>
        </td>
        <td>
          <% if order.payment_state %>
            <span class="pill pill-<%= order.payment_state %>">
              <%= t(order.payment_state, scope: 'spree.payment_states') %>
            </span>
          <% end %>
        </td>
        <!--<% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td>
            <% if order.shipment_state %>
              <span class="pill pill-<%= order.shipment_state %>">
                <%= t(order.shipment_state, scope: 'spree.shipment_states') %>
              </span>
            <% end %>
          </td>
        <% end %>-->
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= order.email %>
          <% end %>
          <%= link_to_with_icon('email', t('spree.actions.send_email'), "mailto:#{order.email}", no_text: true) %>
        </td>
        <td class="align-right"><%= order.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
               resource: Spree::Order,
               new_resource_url: spree.new_admin_order_path %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>